export type DefaultSectionTemplate = {
  title: string;
  type: "text" | "image";
  tags: string[];
};

export const defaultSectionTemplates: DefaultSectionTemplate[] = [
  { title: "Resume de la seance", type: "text", tags: ["summary"] },
  { title: "Objectifs prioritaires", type: "text", tags: ["goals", "planning"] },
  { title: "Points forts", type: "text", tags: ["strengths", "performance"] },
  { title: "Axes d amelioration", type: "text", tags: ["improvements", "performance"] },
  { title: "Planification", type: "text", tags: ["planning"] },
  { title: "Plan 7 jours", type: "text", tags: ["planning"] },
  { title: "Plan 1 mois", type: "text", tags: ["planning"] },
  { title: "Routine pre-shot", type: "text", tags: ["routine", "mental"] },
  { title: "Routine putting", type: "text", tags: ["routine", "putting"] },
  { title: "Statistiques", type: "text", tags: ["stats", "performance"] },
  { title: "Diagnostic swing", type: "text", tags: ["technique", "swing"] },
  { title: "Posture et alignement", type: "text", tags: ["technique", "setup"] },
  { title: "Grip", type: "text", tags: ["technique", "setup"] },
  { title: "Set-up a l adresse", type: "text", tags: ["technique", "setup"] },
  { title: "Tempo et rythme", type: "text", tags: ["technique", "tempo"] },
  { title: "Backswing", type: "text", tags: ["technique", "backswing", "swing"] },
  { title: "Transition", type: "text", tags: ["technique", "transition", "swing"] },
  { title: "Downswing", type: "text", tags: ["technique", "downswing", "swing"] },
  { title: "Impact", type: "text", tags: ["technique", "impact", "swing"] },
  { title: "Finish", type: "text", tags: ["technique", "finish", "swing"] },
  { title: "Contact balle", type: "text", tags: ["technique", "contact"] },
  { title: "Trajectoire / vol", type: "text", tags: ["trajectory", "performance"] },
  { title: "Dispersion", type: "text", tags: ["dispersion", "performance"] },
  { title: "Distance moyenne", type: "text", tags: ["distance", "performance"] },
  { title: "Driver", type: "text", tags: ["driver", "technique"] },
  { title: "Bois et hybrides", type: "text", tags: ["woods", "technique"] },
  { title: "Fers longs", type: "text", tags: ["irons", "technique"] },
  { title: "Fers courts", type: "text", tags: ["irons", "technique"] },
  { title: "Wedges", type: "text", tags: ["wedges", "technique"] },
  { title: "Petit jeu", type: "text", tags: ["short_game", "technique"] },
  { title: "Approches roulees", type: "text", tags: ["short_game", "approach"] },
  { title: "Chips et pitch", type: "text", tags: ["short_game", "chipping", "pitching"] },
  { title: "Bunkers", type: "text", tags: ["short_game", "bunker"] },
  { title: "Putting - mecanique", type: "text", tags: ["putting", "technique"] },
  { title: "Ligne de putt", type: "text", tags: ["putting", "green"] },
  { title: "Dosage / distance control", type: "text", tags: ["putting", "distance"] },
  { title: "Lecture de green", type: "text", tags: ["putting", "green"] },
  { title: "Strategie parcours", type: "text", tags: ["strategy"] },
  { title: "Gestion des risques", type: "text", tags: ["strategy"] },
  { title: "Choix de club", type: "text", tags: ["strategy", "club_choice"] },
  { title: "Strategie tee-shot", type: "text", tags: ["strategy", "driver"] },
  { title: "Tactique sur green", type: "text", tags: ["strategy", "putting"] },
  { title: "Mental - focus", type: "text", tags: ["mental", "focus"] },
  { title: "Gestion du stress", type: "text", tags: ["mental", "stress"] },
  { title: "Confiance et intention", type: "text", tags: ["mental", "confidence"] },
  { title: "Respiration et routine mentale", type: "text", tags: ["mental", "breathing", "routine"] },
  { title: "Physique / mobilite", type: "text", tags: ["physical", "mobility"] },
  { title: "Preparation avant parcours", type: "text", tags: ["prep", "routine"] },
  { title: "Exercices recommandes", type: "text", tags: ["practice", "exercises"] },
  { title: "Images du swing", type: "image", tags: ["visual", "swing"] },
  { title: "Bilan warm-up", type: "text", tags: ["prep", "routine"] },
  { title: "Routine practice", type: "text", tags: ["practice", "routine"] },
  { title: "Echauffement physique", type: "text", tags: ["physical", "prep"] },
  { title: "Mobilite hanches", type: "text", tags: ["physical", "mobility"] },
  { title: "Mobilite epaules", type: "text", tags: ["physical", "mobility"] },
  { title: "Renforcement core", type: "text", tags: ["physical", "strength"] },
  { title: "Stabilite appuis", type: "text", tags: ["physical", "balance"] },
  { title: "Coordination", type: "text", tags: ["physical", "coordination"] },
  { title: "Vitesse de swing", type: "text", tags: ["performance", "swing"] },
  { title: "Regularite", type: "text", tags: ["performance"] },
  { title: "Contact centre de face", type: "text", tags: ["performance", "contact"] },
  { title: "Club path", type: "text", tags: ["technique", "swing"] },
  { title: "Face angle", type: "text", tags: ["technique", "swing"] },
  { title: "Angle d attaque", type: "text", tags: ["technique", "swing"] },
  { title: "Angle de lancement", type: "text", tags: ["trajectory", "performance"] },
  { title: "Spin rate", type: "text", tags: ["stats", "performance"] },
  { title: "Distance carry", type: "text", tags: ["distance", "performance"] },
  { title: "Distance total", type: "text", tags: ["distance", "performance"] },
  { title: "Fairways touches", type: "text", tags: ["stats", "performance"] },
  { title: "Greens en regulation", type: "text", tags: ["stats", "performance"] },
  { title: "Scrambling", type: "text", tags: ["stats", "short_game"] },
  { title: "Putts par trou", type: "text", tags: ["stats", "putting"] },
  { title: "3 putts", type: "text", tags: ["stats", "putting"] },
  { title: "Precision wedge", type: "text", tags: ["wedges", "performance"] },
  { title: "Distance wedges", type: "text", tags: ["wedges", "distance"] },
  { title: "Jeu de fers - trajectoires", type: "text", tags: ["irons", "trajectory"] },
  { title: "Punch shot", type: "text", tags: ["technique", "trajectory"] },
  { title: "Draw / Fade", type: "text", tags: ["technique", "trajectory"] },
  { title: "Controle hauteur", type: "text", tags: ["trajectory", "performance"] },
  { title: "Sorties de rough", type: "text", tags: ["strategy", "short_game"] },
  { title: "Layup decision", type: "text", tags: ["strategy"] },
  { title: "Gestion du vent", type: "text", tags: ["strategy", "performance"] },
  { title: "Gestion des pentes", type: "text", tags: ["strategy", "putting"] },
  { title: "Lecture de lies", type: "text", tags: ["strategy"] },
  { title: "Routine pre-shot competition", type: "text", tags: ["mental", "routine"] },
  { title: "Gestion pression", type: "text", tags: ["mental", "stress"] },
  { title: "Objectif score", type: "text", tags: ["goals", "performance"] },
  { title: "Analyse de partie", type: "text", tags: ["summary", "stats"] },
  { title: "Plan d entrainement", type: "text", tags: ["planning", "practice"] },
  { title: "Volume de practice", type: "text", tags: ["planning", "practice"] },
  { title: "Exercices maison", type: "text", tags: ["practice", "exercises"] },
  { title: "Consignes seance suivante", type: "text", tags: ["planning"] },
  { title: "Feedback coach", type: "text", tags: ["summary"] },
  { title: "Feedback eleve", type: "text", tags: ["summary"] },
  { title: "Materiel conseille", type: "text", tags: ["equipment"] },
  { title: "Grip size", type: "text", tags: ["equipment", "setup"] },
  { title: "Lie/Loft", type: "text", tags: ["equipment", "setup"] },
  { title: "Balles utilisees", type: "text", tags: ["equipment"] },
  { title: "Nutrition hydratation", type: "text", tags: ["physical", "prep"] },
  { title: "Sommeil recuperation", type: "text", tags: ["physical", "recovery"] },
];
