export const RADAR_LOADING_PHRASES = [
  "Analyse des coups les plus propres...",
  "Tri des fléchettes maîtrisées...",
  "Détection des tops et grattes involontaires...",
  "Lecture des trajectoires et du spin...",
  "Mesure des écarts de régularité...",
  "Calibration du carry et du roll...",
  "Décomposition de la vitesse de balle...",
  "Regroupement des impacts consistants...",
  "Inventaire des bons contacts...",
  "Isolation des coups qui volent droit...",
  "Calcul des dispersions latérales...",
  "Vérification des angles de lancement...",
  "Nettoyage des valeurs aberrantes...",
  "Indexation des séries de coups...",
  "Synthèse des variations de spin...",
  "Mise en forme des graphes...",
  "Lecture des impacts de face...",
  "Synchronisation des datas radar...",
  "Recherche des tendances de trajectoire...",
  "Affinage des statistiques de session...",
  "Préparation des graphiques de séance...",
  "Compilation des shots de référence...",
];

export const TPI_LOADING_PHRASES = [
  "Analyse de la mobilité hanches et thorax...",
  "Lecture des amplitudes articulaires...",
  "Vérification de la stabilité et de l'équilibre...",
  "Interprétation du screening physique...",
  "Synthèse des zones à travailler...",
  "Repérage des asymétries...",
  "Évaluation du pattern de rotation...",
  "Calibration de la posture...",
  "Analyse du contrôle pelvien...",
  "Lecture des tests de stabilité...",
  "Regroupement des tests prioritaires...",
  "Préparation du profil de mobilité...",
  "Traitement des scores TPI...",
  "Validation des résultats du screening...",
  "Mise en forme du profil TPI...",
  "Classification des tests par priorité...",
  "Récapitulatif force et mobilité...",
  "Synthèse des limitations clés...",
  "Analyse du contrôle scapulaire...",
  "Vérification des appuis...",
  "Consolidation des observations physiques...",
  "Mise en évidence des points forts...",
];
