create table if not exists public.message_threads (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  workspace_org_id uuid not null references public.organizations(id) on delete cascade,
  student_id uuid references public.students(id) on delete cascade,
  participant_a_id uuid not null references public.profiles(id) on delete cascade,
  participant_b_id uuid not null references public.profiles(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  last_message_id bigint,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint message_threads_kind_check
    check (kind = any (array['student_coach'::text, 'coach_coach'::text])),
  constraint message_threads_participants_distinct
    check (participant_a_id <> participant_b_id),
  constraint message_threads_participants_normalized
    check (participant_a_id < participant_b_id),
  constraint message_threads_student_required
    check (
      (kind = 'student_coach'::text and student_id is not null)
      or (kind = 'coach_coach'::text and student_id is null)
    )
);

create table if not exists public.message_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.message_threads(id) on delete cascade,
  sender_user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  constraint message_messages_body_check
    check (char_length(trim(body)) between 1 and 2000)
);

create table if not exists public.message_thread_members (
  thread_id uuid not null references public.message_threads(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  last_read_message_id bigint references public.message_messages(id) on delete set null,
  last_read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint message_thread_members_pkey primary key (thread_id, user_id)
);

create table if not exists public.message_coach_contact_requests (
  id uuid primary key default gen_random_uuid(),
  requester_user_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  pair_user_a_id uuid not null references public.profiles(id) on delete cascade,
  pair_user_b_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint message_contact_requests_distinct
    check (requester_user_id <> target_user_id),
  constraint message_contact_requests_pair_distinct
    check (pair_user_a_id <> pair_user_b_id),
  constraint message_contact_requests_pair_normalized
    check (pair_user_a_id < pair_user_b_id)
);

create table if not exists public.message_coach_contacts (
  id uuid primary key default gen_random_uuid(),
  user_a_id uuid not null references public.profiles(id) on delete cascade,
  user_b_id uuid not null references public.profiles(id) on delete cascade,
  accepted_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint message_coach_contacts_distinct
    check (user_a_id <> user_b_id),
  constraint message_coach_contacts_pair_normalized
    check (user_a_id < user_b_id)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'message_threads_last_message_id_fkey'
  ) then
    alter table public.message_threads
      add constraint message_threads_last_message_id_fkey
      foreign key (last_message_id) references public.message_messages(id) on delete set null;
  end if;
end
$$;

create unique index if not exists message_threads_unique_kind_student_pair
  on public.message_threads (kind, student_id, participant_a_id, participant_b_id);

create index if not exists message_threads_participant_a_inbox_idx
  on public.message_threads (participant_a_id, last_message_at desc nulls last);

create index if not exists message_threads_participant_b_inbox_idx
  on public.message_threads (participant_b_id, last_message_at desc nulls last);

create index if not exists message_threads_workspace_kind_idx
  on public.message_threads (workspace_org_id, kind, last_message_at desc nulls last);

create index if not exists message_threads_student_idx
  on public.message_threads (student_id);

create index if not exists message_thread_members_user_idx
  on public.message_thread_members (user_id, thread_id);

create index if not exists message_thread_members_unread_idx
  on public.message_thread_members (user_id, last_read_message_id);

create index if not exists message_messages_thread_timeline_idx
  on public.message_messages (thread_id, id desc);

create index if not exists message_messages_sender_thread_idx
  on public.message_messages (sender_user_id, thread_id, id desc);

create unique index if not exists message_coach_contact_requests_pair_unique
  on public.message_coach_contact_requests (pair_user_a_id, pair_user_b_id);

create index if not exists message_coach_contact_requests_target_idx
  on public.message_coach_contact_requests (target_user_id, created_at desc);

create index if not exists message_coach_contact_requests_requester_idx
  on public.message_coach_contact_requests (requester_user_id, created_at desc);

create unique index if not exists message_coach_contacts_pair_unique
  on public.message_coach_contacts (user_a_id, user_b_id);

create index if not exists message_coach_contacts_user_a_idx
  on public.message_coach_contacts (user_a_id, created_at desc);

create index if not exists message_coach_contacts_user_b_idx
  on public.message_coach_contacts (user_b_id, created_at desc);

create or replace function public.sync_message_thread_last_message()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
begin
  update public.message_threads
  set
    last_message_id = new.id,
    last_message_at = new.created_at,
    updated_at = now()
  where id = new.thread_id;

  return new;
end;
$$;

drop trigger if exists sync_message_threads_last_message on public.message_messages;
create trigger sync_message_threads_last_message
after insert on public.message_messages
for each row
execute function public.sync_message_thread_last_message();

drop trigger if exists set_message_threads_updated_at on public.message_threads;
create trigger set_message_threads_updated_at
before update on public.message_threads
for each row
execute function public.set_updated_at();

drop trigger if exists set_message_thread_members_updated_at on public.message_thread_members;
create trigger set_message_thread_members_updated_at
before update on public.message_thread_members
for each row
execute function public.set_updated_at();

alter table public.message_threads enable row level security;
alter table public.message_thread_members enable row level security;
alter table public.message_messages enable row level security;
alter table public.message_coach_contact_requests enable row level security;
alter table public.message_coach_contacts enable row level security;

drop policy if exists message_threads_read on public.message_threads;
create policy message_threads_read
on public.message_threads
for select to authenticated
using (
  exists (
    select 1
    from public.message_thread_members m
    where m.thread_id = message_threads.id
      and m.user_id = auth.uid()
  )
);

drop policy if exists message_threads_no_insert on public.message_threads;
create policy message_threads_no_insert
on public.message_threads
for insert to authenticated
with check (false);

drop policy if exists message_threads_no_update on public.message_threads;
create policy message_threads_no_update
on public.message_threads
for update to authenticated
using (false)
with check (false);

drop policy if exists message_threads_no_delete on public.message_threads;
create policy message_threads_no_delete
on public.message_threads
for delete to authenticated
using (false);

drop policy if exists message_thread_members_read on public.message_thread_members;
create policy message_thread_members_read
on public.message_thread_members
for select to authenticated
using (
  exists (
    select 1
    from public.message_thread_members member
    where member.thread_id = message_thread_members.thread_id
      and member.user_id = auth.uid()
  )
);

drop policy if exists message_thread_members_no_insert on public.message_thread_members;
create policy message_thread_members_no_insert
on public.message_thread_members
for insert to authenticated
with check (false);

drop policy if exists message_thread_members_no_update on public.message_thread_members;
create policy message_thread_members_no_update
on public.message_thread_members
for update to authenticated
using (false)
with check (false);

drop policy if exists message_thread_members_no_delete on public.message_thread_members;
create policy message_thread_members_no_delete
on public.message_thread_members
for delete to authenticated
using (false);

drop policy if exists message_messages_read on public.message_messages;
create policy message_messages_read
on public.message_messages
for select to authenticated
using (
  exists (
    select 1
    from public.message_thread_members m
    where m.thread_id = message_messages.thread_id
      and m.user_id = auth.uid()
  )
);

drop policy if exists message_messages_no_insert on public.message_messages;
create policy message_messages_no_insert
on public.message_messages
for insert to authenticated
with check (false);

drop policy if exists message_messages_no_update on public.message_messages;
create policy message_messages_no_update
on public.message_messages
for update to authenticated
using (false)
with check (false);

drop policy if exists message_messages_no_delete on public.message_messages;
create policy message_messages_no_delete
on public.message_messages
for delete to authenticated
using (false);

drop policy if exists message_coach_contact_requests_read on public.message_coach_contact_requests;
create policy message_coach_contact_requests_read
on public.message_coach_contact_requests
for select to authenticated
using (requester_user_id = auth.uid() or target_user_id = auth.uid());

drop policy if exists message_coach_contact_requests_no_insert on public.message_coach_contact_requests;
create policy message_coach_contact_requests_no_insert
on public.message_coach_contact_requests
for insert to authenticated
with check (false);

drop policy if exists message_coach_contact_requests_no_update on public.message_coach_contact_requests;
create policy message_coach_contact_requests_no_update
on public.message_coach_contact_requests
for update to authenticated
using (false)
with check (false);

drop policy if exists message_coach_contact_requests_no_delete on public.message_coach_contact_requests;
create policy message_coach_contact_requests_no_delete
on public.message_coach_contact_requests
for delete to authenticated
using (false);

drop policy if exists message_coach_contacts_read on public.message_coach_contacts;
create policy message_coach_contacts_read
on public.message_coach_contacts
for select to authenticated
using (user_a_id = auth.uid() or user_b_id = auth.uid());

drop policy if exists message_coach_contacts_no_insert on public.message_coach_contacts;
create policy message_coach_contacts_no_insert
on public.message_coach_contacts
for insert to authenticated
with check (false);

drop policy if exists message_coach_contacts_no_update on public.message_coach_contacts;
create policy message_coach_contacts_no_update
on public.message_coach_contacts
for update to authenticated
using (false)
with check (false);

drop policy if exists message_coach_contacts_no_delete on public.message_coach_contacts;
create policy message_coach_contacts_no_delete
on public.message_coach_contacts
for delete to authenticated
using (false);

alter table public.message_messages replica identity full;
alter table public.message_thread_members replica identity full;

do $$
begin
  begin
    alter publication supabase_realtime add table public.message_messages;
  exception
    when duplicate_object then null;
  end;

  begin
    alter publication supabase_realtime add table public.message_thread_members;
  exception
    when duplicate_object then null;
  end;
end
$$;
